<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Stylo.API\Controllers\" />
    <Folder Include="Stylo.Application\" />
    <Folder Include="Stylo.Domain\" />
    <Folder Include="Stylo.Infrastructure\" />
  </ItemGroup>

</Project>
